namespace txt2png
{
    public static class Constants
    {
        public const string AltText = "Image generated by github.com/3dbrows/txt2png";

        public const string Uri =
            "https://txt2png.azurewebsites.net/txt2png?input=foo%40example.com?background=white";

        public const string Base64OutputForWhiteBackground =
            "iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAMAAACqqpYoAAAAElBMVEWurq4bGxucnJyjo6MAAACPj4+RIAYhAAAAEElEQVQI12NgYGRiYGZhBQAALgAQ2bAGGQAAAABJRU5ErkJggg==";

        public const string Base64OutputForTransparentBackground =
            "iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAMAAACqqpYoAAAABlBMVEX///8AAABVwtN+AAAAAXRSTlMAQObYZgAAAA5JREFUCNdjYGBkYABiAAAQAAOnagnxAAAAAElFTkSuQmCC";

        public const string Base64OutputForBlackBackground =
            "iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAMAAACqqpYoAAAAElBMVEVRUVHk5ORjY2NcXFz///9wcHDL7muBAAAAEElEQVQI12NgYGRiYGZhBQAALgAQ2bAGGQAAAABJRU5ErkJggg==";

        public const string Base64OutputForPunctuation =
            "iVBORw0KGgoAAAANSUhEUgAAAR8AAAAUCAMAAACDOckIAAAABlBMVEX///8AAABVwtN+AAAAAXRSTlMAQObYZgAAAiVJREFUWMPtl9FyhSAMRNn//+l2bq9kk10Q1Acf6rR3HIVkcxKCtHb/Ah4w8tpLo8Pn73v3N+D3/zMOiOHfe/Rn/Z1apFnkZIMrvlcSDeOrS4KzsOdwFE2XXvng4NQFN9INkp3Qx6wg72KbymWDR7KU8ehFz+WGvx6pS4HjQyJZKcJc5VMnEMu2VUCWjzEBHasTt93N+bRjyUEq4+DD0uQV1wqSZ1jfK3yyzjM+dD+KGWZUehAL5SofFMkgP7GYucRs72PRXRQyacQ7yHwOjgu4BpEctdxcFWvhQ9ZVfRKOzCcxjFVlMSzyacLHpDwMKp8+2pYct32/Kov9pj8h15LlLBhbNoxzPjJD1Fvudayrv06v5g5ukRhivn5sm0suwrt8HDg7NZGjXXiLTw1F+MjCdYD8Qkx3Iz45EBSuyHEfNW85Oz4due8/KRNGvsRH/TTvFKa4McVTe81i/WQtNStGhudDDzKfZvjY/px3fM2f+yLITE43ull69MtPdraH+Kgau2f7to9iStuPIdSkkqZkxuVbIwTzia63xOdOf57wcf15NGWJyMiL279i2fIa4Kml/xxDU3AjPkNNUgB8AshZqft7amWbHicchU8/+0XUjZ9w9yiuamU/wSff8qnaf/9Ahd3i01Yrbt1ndb6rdtBAMBxrQt1A9BCfyz6unU/3+Sycv17HZ7SVnPNZGyxfxak5vJ5Pb6eLjXOru7qhm935/1q7fgBtswQIr3FEfgAAAABJRU5ErkJggg==";

        public const string Base64OutputForRiverCrab =
            "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAMAAAAoyzS7AAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAApJREFUCNdjYAAAAAIAAeIhvDMAAAAASUVORK5CYII=";
    }
}